pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu-based VM as the agent

steps:
- script: |
    sudo gpg -k  # Check existing GPG keys (optional)
    
    # Add K6 GPG key for verifying the package
    sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg \
    --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
    
    # Add K6 repository to APT sources
    echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
    
    sudo apt-get update  # Update package list
    sudo apt-get install k6 -y  # Install K6
  displayName: 'Install K6'

- script: k6 run basic_stress.js  # Run your K6 test script
  displayName: 'Run K6 Test'
