{
 "title": "Dashboard Helmut",
 "time": { "from": "2025-03-08T23:41:11.619Z", "to": "2025-03-08T23:44:04.646Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Groups",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "/^$Measurement$/",
     "query": "SELECT count(\"value\"), sum(\"value\") as \"Success Count\",min(\"value\"), median(\"value\"), max(\"value\"), mean(\"value\"), percentile(\"value\", 95) FROM http_req_duration WHERE $timeFilter GROUP BY \"group\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "SELECT sum(value) FROM http_reqs WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P90",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "p90" ] } },
   "targets": [
    {
     "query": "SELECT percentile(value, 90) FROM http_req_duration WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P50",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT percentile(value, 50) FROM http_req_duration WHERE $timeFilter"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Request per Second",
     "query": "SELECT sum(\"value\")\nFROM \"http_reqs\" \nWHERE $timeFilter\nGROUP BY time(3s)"
    },
    {
     "alias": "VUs",
     "query": "SELECT mean(\"value\") \nFROM \"vus\"\nWHERE $timeFilter\nGROUP BY time(3s)"
    },
    {
     "alias": "Response Time",
     "query": "SELECT mean(\"value\") \nFROM \"http_req_duration\" \nWHERE $timeFilter\nGROUP BY time(3s)"
    }
   ]
  },
  {
   "title": "Results",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true
  }
 ]
}